# Generated by Django 4.2.27 on 2025-12-06 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('points_override', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExamTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('instructor', models.CharField(blank=True, max_length=200)),
                ('term', models.CharField(blank=True, max_length=100)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('is_quiz', models.BooleanField(default=False)),
                ('default_points', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('shuffle_answers', models.BooleanField(default=True)),
                ('selection_rules', models.JSONField(default=dict, help_text='Rules for question selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_templates', to='questions.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('version', models.CharField(blank=True, max_length=10)),
                ('latex_file', models.FileField(blank=True, null=True, upload_to='exams/latex/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='exams/pdf/')),
                ('answer_key_pdf', models.FileField(blank=True, null=True, upload_to='exams/keys/')),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('question_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(through='exams.ExamQuestion', to='questions.question')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_exams', to='exams.examtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.generatedexam'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
        migrations.AlterUniqueTogether(
            name='examquestion',
            unique_together={('exam', 'order')},
        ),
    ]
