# Generated by Django 4.2.27 on 2025-12-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtemplate',
            name='default_line_length',
            field=models.CharField(default='3in', max_length=20),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='default_solution_space',
            field=models.CharField(default='2.5in', max_length=20),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='department',
            field=models.CharField(default='Department of Computer Science', max_length=200),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='include_id_field',
            field=models.BooleanField(default=True, help_text='Include student ID field'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='instructions',
            field=models.TextField(blank=True, help_text='Exam instructions/notes'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='max_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='source_file',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='use_checkboxes',
            field=models.BooleanField(default=True, help_text='Use checkboxes for multiple choice'),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='school',
            field=models.CharField(default='Rochester Institute of Technology', max_length=200),
        ),
    ]
