# Generated by Django 4.2.27 on 2025-12-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_add_week_model'),
        ('exams', '0002_examtemplate_default_line_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtemplate',
            name='filter_banks',
            field=models.ManyToManyField(blank=True, related_name='templates', to='questions.questionbank'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='filter_difficulty',
            field=models.CharField(blank=True, help_text='Difficulty level filter', max_length=20),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='filter_question_types',
            field=models.JSONField(blank=True, default=list, help_text='List of question types to include'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='filter_tags',
            field=models.ManyToManyField(blank=True, related_name='templates', to='questions.tag'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='filter_weeks',
            field=models.JSONField(blank=True, default=list, help_text='List of week IDs to include'),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='max_questions',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of questions to select', null=True),
        ),
    ]
