# Generated by Django 4.2.27 on 2025-12-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examtemplate_owner_alter_examtemplate_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtemplate',
            name='max_long_points',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max points from long answer', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='max_mc_points',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max points from multiple choice', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='max_short_points',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max points from short answer', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='max_tf_points',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max points from true/false', max_digits=6, null=True),
        ),
    ]
