# Generated by Django 4.2.27 on 2025-12-11 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quizzes.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0005_add_type_constraints'),
        ('questions', '0008_add_soft_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_code', models.CharField(db_index=True, default=quizzes.models.generate_access_code, max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True, help_text='Instructions shown to students before starting')),
                ('time_limit_minutes', models.PositiveIntegerField(default=60, help_text='Time limit in minutes')),
                ('start_time', models.DateTimeField(blank=True, help_text='When quiz becomes available', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='When quiz closes', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('require_student_id', models.BooleanField(default=True)),
                ('allow_late_submissions', models.BooleanField(default=False)),
                ('late_penalty_percent', models.PositiveIntegerField(default=0, help_text='Penalty percentage per minute late')),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('shuffle_answers', models.BooleanField(default=True)),
                ('show_correct_answers', models.BooleanField(default=False, help_text='Show correct answers after submission')),
                ('show_score_immediately', models.BooleanField(default=True)),
                ('ai_grading_enabled', models.BooleanField(default=True)),
                ('ai_grading_provider', models.CharField(choices=[('claude', 'Claude (Anthropic)'), ('openai', 'GPT-4 (OpenAI)')], default='claude', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL)),
                ('generated_exam', models.ForeignKey(blank=True, help_text='Specific generated exam if using pre-selected questions', null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.generatedexam')),
                ('questions', models.ManyToManyField(blank=True, related_name='quiz_sessions', to='questions.question')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to='exams.examtemplate')),
            ],
            options={
                'verbose_name_plural': 'Quiz Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=200)),
                ('student_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('student_email', models.EmailField(blank=True, max_length=254)),
                ('session_token', models.CharField(max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the timer runs out', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('auto_submitted', models.BooleanField(default=False, help_text='True if timer ran out')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('grading', 'Being Graded'), ('graded', 'Graded'), ('reviewed', 'Reviewed by Instructor')], default='in_progress', max_length=20)),
                ('total_points_possible', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_points_earned', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('percentage_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('late_penalty_applied', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('question_order', models.JSONField(default=list)),
                ('quiz_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quizzes.quizsession')),
            ],
            options={
                'ordering': ['-submitted_at', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScannedExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(upload_to='scanned_exams/')),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('student_name', models.CharField(blank=True, max_length=200)),
                ('student_id', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing OCR'), ('extracted', 'Text Extracted'), ('matched', 'Questions Matched'), ('grading', 'Being Graded'), ('graded', 'Graded'), ('error', 'Error')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('ocr_text', models.JSONField(default=dict)),
                ('ocr_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('extracted_answers', models.JSONField(default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.generatedexam')),
                ('quiz_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scanned_exams', to='quizzes.quizsession')),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_exam', to='quizzes.studentsubmission')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_exams', to='exams.examtemplate')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_number', models.PositiveIntegerField()),
                ('response_data', models.JSONField(default=dict)),
                ('points_possible', models.DecimalField(decimal_places=2, max_digits=5)),
                ('points_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grading_status', models.CharField(choices=[('pending', 'Pending'), ('auto_graded', 'Auto-Graded'), ('ai_graded', 'AI-Graded'), ('manual', 'Manually Graded'), ('overridden', 'Instructor Override')], default='pending', max_length=20)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_feedback', models.TextField(blank=True, help_text='AI-generated feedback for the student')),
                ('ai_reasoning', models.TextField(blank=True, help_text="AI's reasoning (for instructor review)")),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score 0-1', max_digits=3, null=True)),
                ('ai_graded_at', models.DateTimeField(blank=True, null=True)),
                ('ai_model_used', models.CharField(blank=True, max_length=50)),
                ('override_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('override_feedback', models.TextField(blank=True)),
                ('override_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_overrides', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_responses', to='questions.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quizzes.studentsubmission')),
            ],
            options={
                'ordering': ['question_number'],
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
