# Generated by Django 4.2.27 on 2025-12-12 00:15

from django.db import migrations, models
import django.db.models.deletion
import quizzes.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_make_template_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=200)),
                ('student_email', models.EmailField(db_index=True, max_length=254)),
                ('student_id', models.CharField(blank=True, max_length=50)),
                ('code', models.CharField(db_index=True, default=quizzes.models.generate_invitation_code, max_length=12, unique=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.TextField(blank=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='quizzes.quizsession')),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation', to='quizzes.studentsubmission')),
            ],
            options={
                'ordering': ['student_name'],
                'unique_together': {('quiz_session', 'student_email')},
            },
        ),
    ]
