# Generated by Django 4.2.27 on 2025-12-06 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='canonical',
            field=models.ForeignKey(blank=True, help_text='If this is a duplicate, link to the canonical version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_questions', to='questions.question'),
        ),
    ]
