# Generated by Django 4.2.27 on 2025-12-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_canonical'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='questions_q_questio_14b61e_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='questions_q_difficu_5db314_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_bank'], name='questions_q_questio_9dd2a8_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['canonical'], name='questions_q_canonic_a336ec_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-updated_at'], name='questions_q_updated_24ff8a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-created_at'], name='questions_q_created_7d8295_idx'),
        ),
    ]
