# Generated by Django 4.2.27 on 2025-12-06 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_questions_q_questio_14b61e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='variant_number',
            field=models.PositiveIntegerField(default=1, help_text='Variant number within block'),
        ),
        migrations.CreateModel(
            name='QuestionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('max_questions', models.PositiveIntegerField(default=1, help_text='How many questions to pick from this block')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='questions.questionbank')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('question_bank', 'name')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='block',
            field=models.ForeignKey(blank=True, help_text='Group of question variants to pick from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.questionblock'),
        ),
    ]
