# Generated by Django 4.2.27 on 2025-12-07 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_variant_number_questionblock_question_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Week number (1, 2, 3...)')),
                ('name', models.CharField(blank=True, help_text="Custom name like 'Week 1' or 'Introduction'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='questions.course')),
            ],
            options={
                'ordering': ['course', 'number'],
                'unique_together': {('course', 'number')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='week',
            field=models.ForeignKey(blank=True, help_text='Week/module this question belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.week'),
        ),
    ]
