# Generated by Django 4.2.27 on 2026-01-29 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_add_soft_delete'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='questions_q_questio_9dd2a8_idx',
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.questionbank'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['course'], name='questions_q_course__8fa1ea_idx'),
        ),
    ]
