# Generated by Django 4.2.27 on 2026-01-29 15:33

from django.db import migrations


def populate_course(apps, schema_editor):
    """Copy course from question_bank to question.course"""
    Question = apps.get_model('questions', 'Question')
    for question in Question.objects.filter(course__isnull=True, question_bank__isnull=False):
        question.course = question.question_bank.course
        question.save(update_fields=['course'])


def reverse_populate(apps, schema_editor):
    """Reverse: clear course field"""
    Question = apps.get_model('questions', 'Question')
    Question.objects.update(course=None)


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_add_course_to_question'),
    ]

    operations = [
        migrations.RunPython(populate_course, reverse_populate),
    ]
